### ISSUE TITLE
mediamarkt arama

### ISSUE THREAD

**Issue by rsoyxihnark** [saurane/Turkish-Blocklist#2]
||wawlabs.com^

mediamarkt arama fonksiyonunu bozuyor

**Comment by saurane** [comment]
Şuan kontrol edecek durumda değilim. Uzun (3 ay) sürecek ama bakacağım.

**Comment by rsoyxihnark** [comment]
filtreniz adguard tarafından Türk kullanıcılar için default olarak kullanılıyor, aşağıdaki listelerden soruna yol açan domaini çıkartmanızı rica ederim.

https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/adblock-filter.txt
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/adblock.txt
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/dnsmasq.conf
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/domains.txt
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/hosts.txt
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/plain.txt
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/rpz.txt
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/unbound.conf
https://github.com/saurane/Turkish-Blocklist/blob/master/Blocklist/wildcards.txt

**Comment by rsoyxihnark** [comment]
bu sorun hala mevcut.
